### ISSUE TITLE
Cannot install due to missing dependency: getopts

### ISSUE THREAD

**Issue by martin-g** [fisherman/anicode#8]
I'm trying to install with `fisher anicode` but it fails with:

```
Installing 1 plugin/s
OK Copy anicode
Installing 3 dependencies
OK Copy spin
OK Copy get
OK Copy choices
OK Copy getopts
! Fetch getopts github.com/fisherman/getopts
OK Fetch getopts github.com/fisherman/getopts
cp: cannot stat '/home/martin/.cache/fisherman/getopts': No such file or directory
Done in 1s 807ms
```

**Comment by martin-g** [comment]
I worked fine after manual `fisher getopts` but it seems there is something wrong in `fisher`.

**Comment by blissdev** [comment]
Also experienced this issue, and as @martin-g mentioned, installing `getopts` manually fixed the issue.

**Comment by Markcial** [comment]
Unable to dig on this on the moment, maybe on last quarter of january. Sorry

**Comment by Markcial** [comment]
Taking a little bit longer, sorry. Maybe this sunday i will check that bug too.

Thanks for the patience

**Comment by Markcial** [comment]
Solved
